### ISSUE TITLE
Make it possible to set number of decimals in prices

### ISSUE THREAD

**Issue by DonOregano** [Chadsr/waybar-crypto#1]
It would be nice to be able to remove the decimals in the higher-value currencies, to keep it short and sweet.

**Comment by Chadsr** [comment]
Good idea!

I will look into if the CoinMarketCap API is able to take a precision parameter, or otherwise adding a precision for each listed pair would be possible through the module itself.

Will report back / reference here with progress.

Thanks!

**Comment by Chadsr** [comment]
I have added the following feature in v1.1.0. Let me know if it doesn't fully address your request.

Thanks!
