### ISSUE TITLE
More configuration options?

### ISSUE THREAD

**Issue by hertz0022** [chadsr/waybar-crypto#45]
It's a really nice waybar module, the only crypto ticker for now, thanks a lot!
The only throwback noticed is that it can be really space-consuming, especially if configured for more cryptos.
I was thinking it with the main format with only a crypto (e.g. btc) and for a second one, like eth, using the "format-alt" (or the tooltip for even more).
But I think you have to create every time as many variables as there are crypto added for these customizations, right?
Sorry, I don't know Python for now, can't contribute concretely. :(

**Comment by chadsr** [comment]
Hi @hertz0022 , thanks for the feedback!

Agreed, it does take a lot of space up.
Better utilising the `format-alt` option is definitely a good idea. 

Honestly, this script is pretty hacky and rushed. I may find some time soon to clean it up and make it more extensible first. 
After that refactor, I will definitely consider adding "layers", so you can choose if the ticker goes on the main "layer" or the `format-alt` "layer".

Would that satisfy your request?

**Comment by chadsr** [comment]
As a "fix" in the meantime, I can recommend looking into the [Waybar Group Module](https://github.com/Alexays/Waybar/wiki/Module:-Group). This should allow you to play with some form of dynamically hiding modules that are revealed on mouse hover.
