### ISSUE TITLE
Switch to maintained cryptocurrency font repository

### ISSUE THREAD

**Issue by chadsr** [chadsr/waybar-crypto#5]
https://github.com/AllienWorks/cryptocoins is archived and no longer maintained.
So, to support a wider range of cryptocurrency icons, we should investigate switching to another provider, such as https://github.com/spothq/cryptocurrency-icons.

The main issue being, that we require system fonts (ttf), or possibly web fonts (woff), so we may need to convert them.
**OR**
We should figure out if Waybar can support raw svg icons directly, somehow.

**Comment by Chadsr** [comment]
https://github.com/jaywcjlove/svgtofont may be of use in generating a font/webfont file from https://github.com/spothq/cryptocurrency-icons.
