### ISSUE TITLE
Missed dependency AUR

### ISSUE THREAD

**Issue by CelticBoozer** [chadsr/waybar-crypto#91]
The python-poetry package was not added to the dependencies and the build crashes every time. BTW thanks for the great plugin. <3

**Comment by chadsr** [comment]
Strange, `poetry` shouldn't be a dependency beyond for a development environment. The AUR PKGBUILD shouldn't require it at all.

Could you share an error log and which AUR helper you are using (if any)?

**Comment by CelticBoozer** [comment]
Hmm, I have currently fixed this for myself, but give me time, I will try to reproduce this error on a virtual machine.
By the way, I am using `paru`.

**Comment by CelticBoozer** [comment]
I think gist would be the best way to share the installation log.
https://gist.github.com/CelticBoozer/e8e1dc06c672301985a56c7c9fce280f

**Comment by chadsr** [comment]
Thanks!

I must have had a lingering `poetry` package somewhere even when I uninstalled it. Thanks for taking the time to fire up a VM.

Instead of requiring `poetry` I will just remove it in favour of something more general such as `setuptools`

**Comment by chadsr** [comment]
Should be resolved now!

**Comment by CelticBoozer** [comment]
Hi, just tested again on VM, yes, everything works fine, thanks for the quick fix. :D
